### ISSUE TITLE
ModuleNotFoundError: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by Guilherme-Fumagali** [larc-logs-transparentes/tdsc#1]
When running the performance tests for the main verification process for the first time, I encountered the following error:

![image](https://github.com/user-attachments/assets/5af2a915-3d1f-4204-9d87-021875ae789a)

Error description:

```python
Traceback (most recent call last):
  File "/home/gfumagali/Documents/tdsc/client/test_verifications.py", line 1, in <module>
    from verification_scripts import *
  File "/home/gfumagali/Documents/tdsc/client/verification_scripts/data_entry.py", line 1, in <module>
    from tlverifier.merkle_functions.tl_functions import verify_data_entry
  File "/home/gfumagali/Documents/tdsc/.venv/lib/python3.12/site-packages/tlverifier/__init__.py", line 2, in <module>
    from .merkle_functions.data_access import *
  File "/home/gfumagali/Documents/tdsc/.venv/lib/python3.12/site-packages/tlverifier/merkle_functions/data_access.py", line 4, in <module>
    import pkg_resources  # use in package
```

This could indicate that there is either a missing dependency or a problem with the installation of the `setuptools` package. (Source:  https://stackoverflow.com/questions/7446187/no-module-named-pkg-resources?page=1&tab=scoredesc#tab-top)

**Comment by Guilherme-Fumagali** [comment]
Solved running `pip install setuptools` on my environment.
